name: Build
on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
jobs:
  build-linux:
    strategy:
      fail-fast: false
      matrix:
        # only use the latest patch level for all minor versions to reduce number of jobs
        fish:
          - '3.0.0' # since 3.0.0 is the oldest officially supported version it's included as well
          - '3.0.2'
          - '3.1.2'
          - '3.2.2'
          - '3.3.1'
          - '3.4.1'
          - '3.5.1'
          - '3.6.4'
          - '3.7.1'
          - '4.0.0'
    runs-on: ubuntu-latest
    container:
      image: ohmyfish/fish:${{ matrix.fish }}
      options: --user root
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Run tests
        uses: ./.github/actions/run-tests

  build-macos:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - macos-13
          - macos-14
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Run tests
        uses: ./.github/actions/run-tests
