export default {
  "17896441": [() => import(/* webpackChunkName: "17896441" */ "@theme/DocItem"), "@theme/DocItem", require.resolveWeak("@theme/DocItem")],
  "1df93b7f": [() => import(/* webpackChunkName: "1df93b7f" */ "@site/src/pages/index.tsx"), "@site/src/pages/index.tsx", require.resolveWeak("@site/src/pages/index.tsx")],
  "22dd74f7": [() => import(/* webpackChunkName: "22dd74f7" */ "@generated/docusaurus-plugin-content-docs/default/p/index-466.json"), "@generated/docusaurus-plugin-content-docs/default/p/index-466.json", require.resolveWeak("@generated/docusaurus-plugin-content-docs/default/p/index-466.json")],
  "28ab763d": [() => import(/* webpackChunkName: "28ab763d" */ "@site/src/functions/github-api.md"), "@site/src/functions/github-api.md", require.resolveWeak("@site/src/functions/github-api.md")],
  "299d276b": [() => import(/* webpackChunkName: "299d276b" */ "@site/src/functions/git0.md"), "@site/src/functions/git0.md", require.resolveWeak("@site/src/functions/git0.md")],
  "5e95c892": [() => import(/* webpackChunkName: "5e95c892" */ "@theme/DocsRoot"), "@theme/DocsRoot", require.resolveWeak("@theme/DocsRoot")],
  "5e9f5e1a": [() => import(/* webpackChunkName: "5e9f5e1a" */ "@generated/docusaurus.config"), "@generated/docusaurus.config", require.resolveWeak("@generated/docusaurus.config")],
  "68cef36b": [() => import(/* webpackChunkName: "68cef36b" */ "@site/src/functions/modules.md"), "@site/src/functions/modules.md", require.resolveWeak("@site/src/functions/modules.md")],
  "a7456010": [() => import(/* webpackChunkName: "a7456010" */ "@generated/docusaurus-plugin-content-pages/default/__plugin.json"), "@generated/docusaurus-plugin-content-pages/default/__plugin.json", require.resolveWeak("@generated/docusaurus-plugin-content-pages/default/__plugin.json")],
  "a7bd4aaa": [() => import(/* webpackChunkName: "a7bd4aaa" */ "@theme/DocVersionRoot"), "@theme/DocVersionRoot", require.resolveWeak("@theme/DocVersionRoot")],
  "a94703ab": [() => import(/* webpackChunkName: "a94703ab" */ "@theme/DocRoot"), "@theme/DocRoot", require.resolveWeak("@theme/DocRoot")],
  "a9cef9d5": [() => import(/* webpackChunkName: "a9cef9d5" */ "@site/src/functions/fm.md"), "@site/src/functions/fm.md", require.resolveWeak("@site/src/functions/fm.md")],
  "aba21aa0": [() => import(/* webpackChunkName: "aba21aa0" */ "@generated/docusaurus-plugin-content-docs/default/__plugin.json"), "@generated/docusaurus-plugin-content-docs/default/__plugin.json", require.resolveWeak("@generated/docusaurus-plugin-content-docs/default/__plugin.json")],
  "ac46717f": [() => import(/* webpackChunkName: "ac46717f" */ "@site/src/pages/Footer.tsx"), "@site/src/pages/Footer.tsx", require.resolveWeak("@site/src/pages/Footer.tsx")],
  "c3a618e1": [() => import(/* webpackChunkName: "c3a618e1" */ "@site/src/functions/index.md"), "@site/src/functions/index.md", require.resolveWeak("@site/src/functions/index.md")],};
